import streamlit as st
import numpy as np
from PIL import Image
import joblib

# ----------------------------------
# Page Configuration
# ----------------------------------
st.set_page_config(
    page_title="Male vs Female Classifier",
    page_icon="👨👩",
    layout="centered"
)

# ----------------------------------
# Load Model
# ----------------------------------
@st.cache_resource
def load_model():
    return joblib.load("male_female_model.pkl")

try:
    model = load_model()
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop()

IMG_SIZE = 64

# ----------------------------------
# Header
# ----------------------------------
st.markdown(
    """
    <h1 style='text-align:center;color:#4F46E5;'>
    👨 Male vs Female Image Classifier 👩
    </h1>
    """,
    unsafe_allow_html=True
)

st.markdown(
    """
    Upload an image and the model will predict whether
    the face belongs to a Male or Female.
    """
)

st.divider()

# ----------------------------------
# Upload Image
# ----------------------------------
uploaded_file = st.file_uploader(
    "📤 Upload Image",
    type=["jpg", "jpeg", "png"]
)

# ----------------------------------
# Prediction
# ----------------------------------
prediction = model.predict([resized])[0]
probability = model.predict_proba([resized])[0]

if prediction == 0:
    st.success("👨 Male")
else:
    st.success("👩 Female")

st.write(f"👨 Male Probability: {probability[0] * 100:.2f}%")
st.write(f"👩 Female Probability: {probability[1] * 100:.2f}%")
if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    col1, col2 = st.columns(2)

    with col1:
        st.image(image, caption="Uploaded Image", use_container_width=True)

    # Preprocessing
    resized = image.resize((IMG_SIZE, IMG_SIZE))
    resized = np.array(resized)

    # Normalize (remove if not used during training)
    resized = resized / 255.0

    resized = resized.flatten()

    try:
        prediction = model.predict([resized])[0]

        if hasattr(model, "predict_proba"):
            probability = model.predict_proba([resized])[0]
        else:
            probability = None

        with col2:

            st.subheader("Prediction")

            if prediction == 0:
                st.success("👨 Male")
            else:
                st.success("👩 Female")

            if probability is not None:

                st.subheader("Confidence")

                st.write(
                    f"👨 Male: **{probability[0]*100:.2f}%**"
                )

                st.progress(float(probability[0]))

                st.write(
                    f"👩 Female: **{probability[1]*100:.2f}%**"
                )

                st.progress(float(probability[1]))

    except Exception as e:
        st.error(f"Prediction Error: {e}")

# ----------------------------------
# Footer
# ----------------------------------
st.markdown("---")

st.markdown(
    """
    ### 🚀 About Project
    
    This project uses Machine Learning to classify images as
    Male or Female based on facial features.

    **Developed by:** Richeek Pandey
    """
)
# Automatically generated by Colab.

# Original file is located at
#     https:/colab.research.google.com/drive/14_zqkBb_RB7UKtgHV2zMWvNmXV2_OiSg
# """

