# -*- coding: utf-8 -*-
"""Male_vs_Female.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_zqkBb_RB7UKtgHV2zMWvNmXV2_OiSg
"""

import streamlit as st
import numpy as np
from PIL import Image
import joblib

# -------------------------
# Page Configuration
# -------------------------
st.set_page_config(
    page_title="Male vs Female Classifier",
    page_icon="",
    layout="centered"
)

# -------------------------
# Load Model
# -------------------------
model = joblib.load("Male_Female_model.pkl")

IMG_SIZE = 64

st.title("Male vs Female Image Classifier")
st.write("Upload an image to predict whether it is a Male or Female.")

# -------------------------
# Upload Image
# -------------------------
uploaded_file = st.file_uploader(
    "Choose an Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    # Read image using Pillow
    image = Image.open(uploaded_file)

    # Convert to RGB (important if image is grayscale/RGBA)
    image = image.convert("RGB")

    # Display image
    st.image(image, caption="Uploaded Image", width=300)

    # Resize image
    resized = image.resize((IMG_SIZE, IMG_SIZE))

    # Convert to NumPy array
    resized = np.array(resized)

    # Flatten image for Logistic Regression
    resized = resized.flatten()

    # Prediction
    prediction = model.predict([resized])[0]

    probability = model.predict_proba([resized])[0]
    
st.write("Prediction:", prediction)
st.write("Probabilities:", probability)if uploaded_file is not None:

    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_container_width=True)

    img = image.resize((128, 128))
    img = np.array(img)

    if len(img.shape) == 2:
        img = np.stack((img,) * 3, axis=-1)

    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    prediction = model.predict(img)
    prediction = np.argmax(prediction)

    if prediction == 0:
        st.success("👨 Male")
    else:
        st.success("👩 Female")

    st.write("Prediction:", prediction)
# Display prediction
if prediction == 0:
    st.success(" Prediction: Male")
else:
    st.success(" Prediction: Female")
    
# Display probabilities
st.subheader("Prediction Confidence")

st.write(f" Male Probability: **{probability[0] * 100:.2f}%**")
st.write(f" Female Probability: **{probability[1] * 100:.2f}%**")
